
[llm]
api_type = "openai"
model = "gpt-4"
base_url = "https://api.openai.com/v1/"
api_key = "test-key"
max_tokens = 8192
temperature = 0.0

[llm.vision]
api_type = "openai"
model = "gpt-4-vision-preview"
base_url = "https://api.openai.com/v1/"
api_key = "test-key"
max_tokens = 8192
temperature = 0.0
